# Generated by Django 4.0.4 on 2022-05-31 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
