# Generated by Django 4.0.4 on 2022-05-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='desc',
            new_name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=22, max_length=15),
            preserve_default=False,
        ),
    ]
